spring.config.import=optional:file:.env[.properties]
spring.application.name=budgeting

spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=google/gemma-4-26b-a4b-it:free
spring.ai.openai.chat.response-format.type=TEXT

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.audio.api-key=${AUDIO_API_KEY}